# Network policies file, using Cilium
---
# Default deny policy. Before specific policies, we need to deny everything else.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: development
spec:
  endpointSelector:
    matchLabels: {} # Applies to all pods
  ingress: [] # No ingress rules: Everything incoming is blocked
  egress: []  # No egress rules: Everything outgoing is blocked
---
# Policy that specifies allowed communications
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: aegis-network-policy
  namespace: development
spec:
  # 1. Select the destination pods
  endpointSelector:
    matchLabels:
      app: backend
  # 2. Ingress rules (incoming traffic)
  ingress:
    # Allow traffic only from pods labeled "app:frontend"
    - fromEndpoints:
        - matchLabels:
            app: frontend
      toPorts:
        - ports:
            # Limit communication to port 8080 (TCP)
            - port: '8080'
              protocol: TCP
          rules:
            http:
              # Layer 7 rule (HTTP): Allow only specific API
              - method: GET
                path: /api/v1/public