apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aegis-example-pvc
  namespace: development
spec:
  accessModes:
    # See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - ReadWriteOnce
  resources:
    requests:
      # Enter required storage
      storage: 1Gi