# Persistent Volume Claim (PVC): Used to claim persistent storage 
# within the cluster and the 'development' namespace,
# abstracting the underlying infrastructure from the application
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aegis-example-pvc
  namespace: development
spec:
  accessModes:
    # ReadWriteOnce (RWO): Volume can be mounted as read-write by a single node
    # See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - ReadWriteOnce
  resources:
    requests:
      # Enter required storage
      storage: 1Gi