# ================================================================================================
# Secrets file: used to store sensitive application credentials, tokens, and private keys securely
# ================================================================================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: development
type: Opaque
data: # Option 1: Secrets in this section must be base64-encoded
  DB_PASSWORD: "c3VwZXJzZWNyZXRwYXNzd29yZDEyMw==" # Literally 'supersecretpassword123'
stringData: # Option 2: Plain text values
  API_KEY: "super-secret-key-123456"